name: colx_523
channels:
  - conda-forge
dependencies:
  - conda
  - python=3.12
  - pandas
  - numpy
  - feedparser
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-spellchecker
  - matplotlib
  - nltk
  - fastapi
  - scikit-learn
  - statsmodels
  - whoosh
  - uvicorn
  - requests
  - pip
  - pip:
    - protobuf<=3.20.3
    - altair<5
    - streamlit>=1.28
