name: colx_523
channels:
  - conda-forge
dependencies:
  - conda
  - python=3.12
  - pandas
  - numpy
  - feedparser
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-spellchecker
  - matplotlib
  - nltk
  - fastapi
  - streamlit
  - scikit-learn
  - statsmodels
